apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ffmm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ffmm
    app.kubernetes.io/part-of: byoc-app-uqxh
  name: ffmm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: ffmm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: ffmm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-doaj-tenant/byoc-app-uqxh/ffmm@sha256:9730be15ca33dc598611e946177b8823c97097f787c2972ede1b59de87d690a6
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
