apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ffmm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ffmm
    app.kubernetes.io/part-of: byoc-app-uqxh
  name: ffmm
spec:
  rules:
  - host: ffmm-byoc-doaj-tenant.apps.3bce4957dafb2911a136.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: ffmm
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
